import TotalVendors from "../components/crm/TotalVendors";
import React from "react";
import type { Metadata } from "next";
import VendorsProperties from "../components/crm/VendorsProperties";

export const metadata: Metadata = {
  title: "CRM Dashboard",
  description: "Generated by create next app",
};

const Crm = () => {
  return (
    <div className="p-0 sm:p-6 md:p-8">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-4 col-span-12">
          <TotalVendors />
        </div>
        <div className="lg:col-span-4 col-span-12">
          <VendorsProperties />
        </div>
      </div>
    </div>
  );
};

export default Crm;
