import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import AuthRedirector from "../app/login/authRedirector";
import MySidebar from "./components/Sidebar";

import { CustomizerContextProvider } from "./components/shared/CustomizerContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vendor List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <CustomizerContextProvider>
          <AuthRedirector />
          <Navbar />

          <div className="flex min-h-screen relative">
            {/* Sidebar */}
            <div className="sticky top-0 h-screen z-[9999]">
              <MySidebar />
            </div>

            {/* Main Page Content */}
            <main className="flex-1 p-4 overflow-auto">{children}</main>
          </div>
        </CustomizerContextProvider>
      </body>
    </html>
  );
}
