import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import AuthRedirector from "../app/login/authRedirector";
import MySidebar from "./components/Sidebar";
import NextTopLoader from "nextjs-toploader";

import { CustomizerContextProvider } from "./components/shared/CustomizerContext";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FestGo Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <CustomizerContextProvider>
          <AuthRedirector />
          <NextTopLoader color="#1447e6" showSpinner={false} />
          <Navbar />

          <div className="flex min-h-screen relative">
            <div className="sticky top-0 h-screen z-[500]">
              <MySidebar />
            </div>

            <main className="flex-1 p-4 overflow-auto">{children}</main>
          </div>

          {/* Toastify Notifications */}
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
        </CustomizerContextProvider>
      </body>
    </html>
  );
}
